### ISSUE TITLE
Fails simple test case

### ISSUE THREAD

**Issue by kjkjava** [w01fe/hungarian#1]
Hey there,

Maybe I'm using it wrong, but a simple test case (from [wikiHow](http://www.wikihow.com/Use-the-Hungarian-Algorithm)) puts the program into an infinite loop between Step 4 and Step 6.  Here is the main method to test it out:

``` java
public static void main(String [] args) {
    double[][] matrix = {{10, 19, 8, 15},
                         {10, 18, 7, 17},
                         {13, 16, 9, 14},
                         {12, 19, 8, 18},
                         {14, 17, 10, 19}};
    System.out.println(hgAlgorithm(matrix, "min"));
}
```

Any ideas as to what might be going on?

**Comment by w01fe** [comment]
I'm not sure -- I didn't write the code, just put it on github.  That said, I've used it a lot and never run into this issue, but I always ran it on square matrices.  

It seems like just padding your matrix with a column of zeros to make it 5x5 fixes the problem, and gets the correct answer of 48.  I have no idea why the code doesn't test for this and throw if it does assume it -- I'm happy to accept pull requests :).

**Comment by kjkjava** [comment]
Ah, of course!  I've seen automatic padding dealt with in some implementations, but I didn't even notice that my test case wasn't square!  I'll submit a pull request soon.  Thanks for the help!

**Comment by w01fe** [comment]
No problem -- looking forward to the pull request, thanks!
